/* Auto-generated by genmsg_cpp for file /home/user/fuerte_workspace/sandbox/PanTilt/DPPanTilt_msgs/msg/ReportDynamicInfo.msg */
#ifndef DPPANTILT_MSGS_MESSAGE_REPORTDYNAMICINFO_H
#define DPPANTILT_MSGS_MESSAGE_REPORTDYNAMICINFO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace DPPanTilt_msgs
{
template <class ContainerAllocator>
struct ReportDynamicInfo_ {
  typedef ReportDynamicInfo_<ContainerAllocator> Type;

  ReportDynamicInfo_()
  : header()
  , currentlyInPositionControl(false)
  , panPositionInRadians(0.0)
  , tiltPositionInRadians(0.0)
  , panVelocityInRadiansPerSec(0.0)
  , tiltVelocityInRadiansPerSec(0.0)
  {
  }

  ReportDynamicInfo_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , currentlyInPositionControl(false)
  , panPositionInRadians(0.0)
  , tiltPositionInRadians(0.0)
  , panVelocityInRadiansPerSec(0.0)
  , tiltVelocityInRadiansPerSec(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _currentlyInPositionControl_type;
  uint8_t currentlyInPositionControl;

  typedef float _panPositionInRadians_type;
  float panPositionInRadians;

  typedef float _tiltPositionInRadians_type;
  float tiltPositionInRadians;

  typedef float _panVelocityInRadiansPerSec_type;
  float panVelocityInRadiansPerSec;

  typedef float _tiltVelocityInRadiansPerSec_type;
  float tiltVelocityInRadiansPerSec;


  typedef boost::shared_ptr< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ReportDynamicInfo
typedef  ::DPPanTilt_msgs::ReportDynamicInfo_<std::allocator<void> > ReportDynamicInfo;

typedef boost::shared_ptr< ::DPPanTilt_msgs::ReportDynamicInfo> ReportDynamicInfoPtr;
typedef boost::shared_ptr< ::DPPanTilt_msgs::ReportDynamicInfo const> ReportDynamicInfoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace DPPanTilt_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2b3f54532ce42444329f3bb657130369";
  }

  static const char* value(const  ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2b3f54532ce42444ULL;
  static const uint64_t static_value2 = 0x329f3bb657130369ULL;
};

template<class ContainerAllocator>
struct DataType< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "DPPanTilt_msgs/ReportDynamicInfo";
  }

  static const char* value(const  ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#\n\
# COPYRIGHT (C) 2005-2010\n\
# RE2, INC.\n\
# ALL RIGHTS RESERVED\n\
#\n\
# This is free software:\n\
# you can redistribute it and/or modify it under the terms of the GNU General\n\
# Public License as published by the Free Software Foundation, either version\n\
# 3 of the License, or (at your option) any later version.\n\
#\n\
# You should have received a copy of the GNU General Public License along\n\
# with this package.  If not, see <http://www.gnu.org/licenses/>.\n\
#\n\
# RE2, INC. disclaims all warranties with regard to this software, including\n\
# all implied warranties of merchantability and fitness, in no event shall\n\
# RE2, INC. be liable for any special, indirect or consequential damages or\n\
# any damages whatsoever resulting from loss of use, data or profits, whether\n\
# in an action of contract, negligence or other tortious action, arising out\n\
# of or in connection with the use or performance of this software.\n\
#\n\
#\n\
#\n\
\n\
# This message is used to report the information about the Pan/Tilt unit\n\
# that will be changing as the unit is used.\n\
\n\
Header header\n\
\n\
# This bool marks whether or not the unit is in Position Control.  If it\n\
# is not, this means the unit is in Velocity Control.\n\
bool currentlyInPositionControl\n\
\n\
# These are the last recorded positions of the axes\n\
float32 panPositionInRadians\n\
float32 tiltPositionInRadians\n\
\n\
# These are the last recorded velocities of the axes\n\
float32 panVelocityInRadiansPerSec\n\
float32 tiltVelocityInRadiansPerSec\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.currentlyInPositionControl);
    stream.next(m.panPositionInRadians);
    stream.next(m.tiltPositionInRadians);
    stream.next(m.panVelocityInRadiansPerSec);
    stream.next(m.tiltVelocityInRadiansPerSec);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ReportDynamicInfo_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::DPPanTilt_msgs::ReportDynamicInfo_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "currentlyInPositionControl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.currentlyInPositionControl);
    s << indent << "panPositionInRadians: ";
    Printer<float>::stream(s, indent + "  ", v.panPositionInRadians);
    s << indent << "tiltPositionInRadians: ";
    Printer<float>::stream(s, indent + "  ", v.tiltPositionInRadians);
    s << indent << "panVelocityInRadiansPerSec: ";
    Printer<float>::stream(s, indent + "  ", v.panVelocityInRadiansPerSec);
    s << indent << "tiltVelocityInRadiansPerSec: ";
    Printer<float>::stream(s, indent + "  ", v.tiltVelocityInRadiansPerSec);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DPPANTILT_MSGS_MESSAGE_REPORTDYNAMICINFO_H

