(cl:in-package DPPanTilt_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CURRENTLYINPOSITIONCONTROL-VAL
          CURRENTLYINPOSITIONCONTROL
          PANPOSITIONINRADIANS-VAL
          PANPOSITIONINRADIANS
          TILTPOSITIONINRADIANS-VAL
          TILTPOSITIONINRADIANS
          PANVELOCITYINRADIANSPERSEC-VAL
          PANVELOCITYINRADIANSPERSEC
          TILTVELOCITYINRADIANSPERSEC-VAL
          TILTVELOCITYINRADIANSPERSEC
))