(cl:in-package DPPanTilt_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          PANMINIMUMVALIDPOSITIONINRADIANS-VAL
          PANMINIMUMVALIDPOSITIONINRADIANS
          TILTMINIMUMVALIDPOSITIONINRADIANS-VAL
          TILTMINIMUMVALIDPOSITIONINRADIANS
          PANMAXIMUMVALIDPOSITIONINRADIANS-VAL
          PANMAXIMUMVALIDPOSITIONINRADIANS
          TILTMAXIMUMVALIDPOSITIONINRADIANS-VAL
          TILTMAXIMUMVALIDPOSITIONINRADIANS
          PANLOWERSPEEDBOUNDINRADIANSPERSEC-VAL
          PANLOWERSPEEDBOUNDINRADIANSPERSEC
          TILTLOWERSPEEDBOUNDINRADIANSPERSEC-VAL
          TILTLOWERSPEEDBOUNDINRADIANSPERSEC
          PANUPPERSPEEDBOUNDINRADIANSPERSEC-VAL
          PANUPPERSPEEDBOUNDINRADIANSPERSEC
          TILTUPPERSPEEDBOUNDINRADIANSPERSEC-VAL
          TILTUPPERSPEEDBOUNDINRADIANSPERSEC
))